SELECT A.FLAVOR
FROM (SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
      FROM FIRST_HALF
     GROUP BY FLAVOR
     ) A JOIN 
     (SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
      FROM JULY
      GROUP BY FLAVOR) B
ON A.SHIPMENT_ID = B.SHIPMENT_ID
ORDER BY A.TOTAL + B.TOTAL DESC
LIMIT 3;